### ISSUE TITLE
RabbitMQ public signing key no longer available

### ISSUE THREAD

**Issue by orls** [alexey-medvedchikov/ansible-rabbitmq#15]
The apt key http://www.rabbitmq.com/rabbitmq-signing-key-public.asc is no longer available, and the [rabbitMQ docs](https://www.rabbitmq.com/install-debian.html) now refer to a [slightly different key URL](https://www.rabbitmq.com/rabbitmq-release-signing-key.asc)

**Comment by veger** [comment]
I guess this is fixed by #17 (at least for me it is working)
